'use client';

import { useEffect, useMemo, useState } from 'react';

type Player = { id: string; name: string; color: 'red' | 'yellow' };
type ChatMessage = { id: string; name: string; text: string };
type Room = { code: string; hostId: string; players: Player[]; status: 'lobby' | 'playing' | 'finished'; board: (null | 'red' | 'yellow')[]; turn: 'red' | 'yellow'; winner: string | null; messages: ChatMessage[] };

const emptyBoard = () => Array(42).fill(null) as Room['board'];
const appwriteReady = Boolean(process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT && process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID && process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID && process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_ID);
const key = 'bored-board-room';

function newRoom(hostName: string): Room { const hostId = crypto.randomUUID(); return { code: Math.random().toString(36).slice(2, 8).toUpperCase(), hostId, players: [{ id: hostId, name: hostName, color: 'red' }], status: 'lobby', board: emptyBoard(), turn: 'red', winner: null, messages: [] }; }
function checkWinner(board: Room['board'], index: number) { const color = board[index]; if (!color) return false; const row = Math.floor(index / 7), col = index % 7; return [[0,1],[1,0],[1,1],[1,-1]].some(([dr,dc]) => { let count=1; for (const sign of [-1,1]) for (let step=1;step<4;step++){const r=row+dr*step*sign,c=col+dc*step*sign;if(r>=0&&r<6&&c>=0&&c<7&&board[r*7+c]===color)count++;else break;} return count>=4; }); }
async function appwriteRequest(room: Room, method: 'POST' | 'PATCH', documentId: string) { if (!appwriteReady) return; const endpoint = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!.replace(/\/$/,''); const url = `${endpoint}/databases/${process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID}/collections/${process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_ID}/documents${method==='PATCH'?`/${documentId}`:''}`; await fetch(url,{method,headers:{'Content-Type':'application/json','X-Appwrite-Project':process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!},body:JSON.stringify({documentId:method==='POST'?documentId:undefined,data:{roomCode:room.code,hostId:room.hostId,players:JSON.stringify(room.players),status:room.status,board:JSON.stringify(room.board),turn:room.turn,winner:room.winner,messages:JSON.stringify(room.messages),updatedAt:Date.now()},permissions:['read("any")','update("any")']})}); }

export default function Home() {
  const [view,setView]=useState<'home'|'host-guide'|'lobby'|'game'>('home'); const [name,setName]=useState(''); const [codeInput,setCodeInput]=useState(''); const [chatInput,setChatInput]=useState(''); const [room,setRoom]=useState<Room|null>(null); const [playerId,setPlayerId]=useState(''); const [copied,setCopied]=useState(false); const [message,setMessage]=useState('');
  const isHost=room?.hostId===playerId; const currentPlayer=room?.players.find(p=>p.id===playerId); const joinCode=useMemo(()=>new URLSearchParams(typeof window!=='undefined'?window.location.search:'').get('room'),[]);
  useEffect(()=>{const saved=localStorage.getItem(key);if(saved)try{const parsed=JSON.parse(saved);setRoom({...parsed,messages:parsed.messages??[]});}catch{}if(joinCode)setCodeInput(joinCode);},[joinCode]); useEffect(()=>{if(room)localStorage.setItem(key,JSON.stringify(room));},[room]);
  useEffect(()=>{if(!room||!appwriteReady)return;const poll=setInterval(async()=>{try{const ep=process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!.replace(/\/$/,'');const res=await fetch(`${ep}/databases/${process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID}/collections/${process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_ID}/documents/${room.code}`,{headers:{'X-Appwrite-Project':process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!}});if(res.ok){const doc=await res.json();setRoom({...room,...doc.data,players:JSON.parse(doc.data.players),board:JSON.parse(doc.data.board),messages:doc.data.messages?JSON.parse(doc.data.messages):[]});}}catch{}},1800);return()=>clearInterval(poll);},[room?.code]);
  function host(){const next=newRoom(name.trim()||'River');setRoom(next);setPlayerId(next.hostId);setView('lobby');void appwriteRequest(next,'POST',next.code);}
  function sendMessage(){const text=chatInput.trim();if(!room||!text||!currentPlayer)return;const next={...room,messages:[...(room.messages??[]).slice(-49),{id:crypto.randomUUID(),name:currentPlayer.name,text:text.slice(0,140)}]};setChatInput('');setRoom(next);void appwriteRequest(next,'PATCH',next.code);}
  async function join(){const code=codeInput.trim().toUpperCase();if(!code)return setMessage('Enter a room code first.');let saved=room?.code===code?room:null;if(appwriteReady){try{const ep=process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!.replace(/\/$/,'');const query=encodeURIComponent(`equal("roomCode",["${code}"])`);const res=await fetch(`${ep}/databases/${process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID}/collections/${process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_ID}/documents?queries[]=${query}`,{headers:{'X-Appwrite-Project':process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!}});if(res.ok){const docs=await res.json();const data=docs.documents?.[0]?.data;if(data)saved={...data,players:JSON.parse(data.players),board:JSON.parse(data.board)};}}catch{}}if(saved){if(saved.players.length>=2)return setMessage('That room is full.');const next={...saved,players:[...saved.players,{id:crypto.randomUUID(),name:name.trim()||'Guest',color:'yellow' as const}]};setRoom(next);setPlayerId(next.players[1].id);setView('lobby');void appwriteRequest(next,'PATCH',code);}else setMessage(appwriteReady?'Room not found. Check the code and try again.':'Room not found in this demo. Connect Appwrite to share rooms across devices.');}
  function start(){if(!room||room.players.length<2)return;const next={...room,status:'playing' as const};setRoom(next);setView('game');void appwriteRequest(next,'PATCH',next.code);}
  function drop(col:number){if(!room||room.status!=='playing'||room.winner||room.turn!==currentPlayer?.color)return;let row=-1;for(let r=5;r>=0;r--)if(!room.board[r*7+col]){row=r;break;}if(row<0)return;const index=row*7+col,board=[...room.board];board[index]=room.turn;const won=checkWinner(board,index);const next={...room,board,winner:won?currentPlayer.name:(board.every(Boolean)?'draw':null),status:(won||board.every(Boolean))?'finished' as const:room.status,turn:room.turn==='red'?'yellow' as const:'red' as const};setRoom(next);void appwriteRequest(next,'PATCH',next.code);}
  function reset(){if(!room)return;const next={...room,status:'playing' as const,board:emptyBoard(),turn:'red' as const,winner:null};setRoom(next);setView('game');void appwriteRequest(next,'PATCH',next.code);}
  async function share(){const url=`${window.location.origin}${window.location.pathname}?room=${room?.code}`;try{await navigator.clipboard.writeText(url);setCopied(true);setTimeout(()=>setCopied(false),1800);}catch{}}
  if(room && !room.messages) room.messages=[];
  const board=room?.board??emptyBoard(); const chatMessages=room?.messages??[];
  return <main className="site-shell"><nav className="topbar"><div className="brand"><span className="brand-mark">✦</span><span>Bored Board Games</span></div><span className="tiny-status"><i/> {appwriteReady?'live rooms':'demo mode'}</span></nav>
    {view==='home'&&<section className="hero"><div className="hero-copy"><p className="eyebrow">THE GROUP CHAT IS WAITING</p><h1>Get mad at <em>Uno</em> anywhere, anytime.</h1><p className="lede">Simple games for friends who are tired of deciding what to play.</p><div className="hero-actions"><button className="primary" onClick={()=>setView('host-guide')}>Host a game <span>↗</span></button><button className="secondary" onClick={()=>setView('lobby')}>Join with a code</button></div><p className="no-signup"><span>✦</span> No account. No downloads. Just play.</p></div><div className="hero-art"><div className="scribble">your move<br/>bestie</div><div className="float-card card-red">✕</div><div className="float-card card-yellow">●</div><div className="float-card card-blue">◆</div><div className="mini-board">{Array.from({length:16},(_,i)=><span key={i} className={i%5===0?'mini-dot red-dot':i%7===0?'mini-dot yellow-dot':''}/>)}</div></div></section>}
    {view==='host-guide'&&<section className="host-guide"><button className="text-button back" onClick={()=>setView('home')}>← Back home</button><div className="section-heading"><p className="eyebrow">HOST A GAME</p><h2>Three tiny steps.<br/><em>Big table energy.</em></h2><p>Set up a room in under a minute, then get back to arguing about the rules.</p></div><div className="process-grid"><div className="process-step"><span className="step-number">01</span><span className="step-icon">☺</span><h3>Pick a name</h3><p>Choose the nickname your friends will see at the table.</p></div><div className="process-step"><span className="step-number">02</span><span className="step-icon blue-icon">↗</span><h3>Share the invite</h3><p>Copy your room link or code and drop it in the group chat.</p></div><div className="process-step"><span className="step-number">03</span><span className="step-icon yellow-icon">✦</span><h3>Start the game</h3><p>When one friend joins, hit start. The board opens for everyone.</p></div></div><button className="primary guide-cta" onClick={()=>setView('lobby')}>Let’s make a room <span>→</span></button></section>}
    {view==='lobby'&&<section className="lobby"><div className="section-heading"><p className="eyebrow">WELCOME TO THE TABLE</p><h2>{room?'Your room is ready.':'Pick a seat, make a room.'}</h2><p>{room?'Send the invite and wait for your favorite rivals.':'Use a nickname, then host a room or hop into a friend’s.'}</p></div>{!room&&<div className="lobby-grid"><div className="panel accent-panel"><span className="panel-icon">✦</span><h3>Host a game</h3><p>Start a room and send the link to your group chat.</p><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your display name" maxLength={20}/><button className="primary full" onClick={host}>Create room <span>↗</span></button></div><div className="panel"><span className="panel-icon muted">→</span><h3>Join a game</h3><p>Got a code from a friend? You’re one move away.</p><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your display name" maxLength={20}/><input value={codeInput} onChange={e=>setCodeInput(e.target.value)} placeholder="Room code" maxLength={6}/><button className="secondary full" onClick={join}>Join room</button></div></div>}{room&&<div className="room-card"><div className="room-top"><div><span className="eyebrow">ROOM CODE</span><div className="room-code">{room.code}</div></div><button className="share-button" onClick={share}>{copied?'Copied!':'Copy invite link'} <span>↗</span></button></div><div className="player-list"><div className="list-label">PLAYERS <span>{room.players.length}/2</span></div>{room.players.map(p=><div className="player-row" key={p.id}><span className={`avatar ${p.color}`}>{p.name.slice(0,1).toUpperCase()}</span><span>{p.name}{p.id===room.hostId&&<small>HOST</small>}</span><i className="ready-dot"/></div>)}{room.players.length<2&&<div className="waiting">Waiting for one more player<span>...</span></div>}</div><div className="chat-box"><div className="chat-head"><span>ROOM CHAT</span><small>{appwriteReady?'SYNCED':'LOCAL'}</small></div><div className="chat-messages">{room.messages.length===0?<p className="chat-empty">Say something while you wait...</p>:room.messages.map(m=><p key={m.id}><b>{m.name}</b> {m.text}</p>)}</div><div className="chat-compose"><input value={chatInput} onChange={e=>setChatInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendMessage()} placeholder="Message the table..." maxLength={140}/><button onClick={sendMessage} aria-label="Send message">↑</button></div></div>{isHost?<button className="primary start-button" disabled={room.players.length<2} onClick={start}>{room.players.length<2?'Waiting for players':'Start game'} <span>→</span></button>:<p className="center-note">The host will start the game when everyone is here.</p>}<button className="text-button" onClick={()=>{setRoom(null);setView('home');}}>Leave room</button></div>}{message&&<p className="message">{message}</p>}</section>}
    {view==='game'&&room&&<section className="game-layout"><div className="game-head"><div><p className="eyebrow">CONNECT FOUR · ROOM {room.code}</p><h2>{room.winner?(room.winner==='draw'?'A perfectly messy draw.':`${room.winner} wins!`):`${room.players.find(p=>p.color===room.turn)?.name}'s turn`}</h2></div><button className="share-button" onClick={share}>{copied?'Copied!':'Invite a friend'} ↗</button></div><div className="game-content"><div className="board-shell"><div className="board-labels">{Array.from({length:7},(_,c)=><button key={c} aria-label={`Drop in column ${c+1}`} onClick={()=>drop(c)}>↓</button>)}</div><div className="board">{board.map((cell,i)=><button key={i} className={`slot ${cell??''}`} onClick={()=>drop(i%7)} aria-label={`Row ${Math.floor(i/7)+1}, column ${(i%7)+1}`}><span/></button>)}</div></div><aside className="score-panel"><p className="eyebrow">AT THE TABLE</p>{room.players.map(p=><div className="score-row" key={p.id}><span className={`avatar ${p.color}`}>{p.name.slice(0,1).toUpperCase()}</span><div><b>{p.name}</b><small>{p.color===room.turn&&!room.winner?'YOUR TURN':p.id===room.hostId?'HOST':'PLAYER'}</small></div></div>)}<div className="chat-box"><div className="chat-head"><span>ROOM CHAT</span><small>{appwriteReady?'SYNCED':'LOCAL'}</small></div><div className="chat-messages">{room.messages.length===0?<p className="chat-empty">Cheer, taunt, or say “nice move.”</p>:room.messages.map(m=><p key={m.id}><b>{m.name}</b> {m.text}</p>)}</div><div className="chat-compose"><input value={chatInput} onChange={e=>setChatInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendMessage()} placeholder="Message the table..." maxLength={140}/><button onClick={sendMessage} aria-label="Send message">↑</button></div></div><div className="rules"><b>How to play</b><p>Drop four of your pieces in a row — across, down, or diagonal.</p></div>{room.winner&&<button className="primary full" onClick={reset}>Play again <span>↻</span></button>}</aside></div><button className="text-button back" onClick={()=>setView('lobby')}>← Back to room</button></section>}
    <footer><span>Made for the group chat.</span><span>One game. Zero overthinking.</span></footer></main>;
}
